/* Generated by AN DISI Unibo */ 
package it.unibo.trolleyactor

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Trolleyactor ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				it.unibo.parkingmanagerservice.utility.MapLoader.loadMapFromTxt("resources/parking_map.txt")
				val STEP_TIME = "340"
				val PLANNER = itunibo.planner.plannerUtil
				val PARKING_SLOT_MAP = it.unibo.parkingmanagerservice.repository.parkingslot.ParkingSlotMap
				val DOOR_MAP = it.unibo.parkingmanagerservice.repository.door.DoorMap
				val INDOOR = it.unibo.parkingmanagerservice.entity.door.DoorType.INDOOR
				val OUTDOOR = it.unibo.parkingmanagerservice.entity.door.DoorType.OUTDOOR
				val IN_POSITION = DOOR_MAP.getAdiacentAllowedPositionByDoorType(INDOOR)!!
				val OUT_POSITION = DOOR_MAP.getAdiacentAllowedPositionByDoorType(OUTDOOR)!!
				var DEST : Pair<Int, Int>? = null
				var TRIP_BUILDER = it.unibo.parkingmanagerservice.utility.TripBuilder(IN_POSITION.first, IN_POSITION.second, OUT_POSITION.first, OUT_POSITION.second)
				var TRIP : kotlin.collections.Iterator<it.unibo.parkingmanagerservice.entity.trolley.TripStage>? = null
				var PLAN : kotlin.collections.Iterator<aima.core.agent.Action>? = null
				var ACTION : aima.core.agent.Action? = null
				var CURR_STAGE : it.unibo.parkingmanagerservice.entity.trolley.TripStage? = null
				var CAN_GO = false
				var STATE = it.unibo.parkingmanagerservice.entity.trolley.TrolleyState.IDLE
				var INTERRUPT = false
				var EXPECTED_DIRECTION : String? = null
				var PAYLOAD = ""
				
				PLANNER.initAI()
				PLANNER.showMap()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name | Started...")
					}
					 transition( edgeName="goto",targetState="home", cond=doswitch() )
				}	 
				state("home") { //this:State
					action { //it:State
						println("$name | Home")
						
									TRIP = null
									PLAN = null
									CURR_STAGE = null
									STATE = `it.unibo.parkingmanagerservice.entity.trolley`.TrolleyState.IDLE	
									
									PLANNER.showMap()
									PAYLOAD = "{\"state\": \"${STATE}\", \"action\": \"${CURR_STAGE?.type}\", \"position\": {\"x\": \"${PLANNER.getPosX()}\", \"y\": \"${PLANNER.getPosY()}\"}}"
						updateResourceRep( PAYLOAD  
						)
					}
					 transition(edgeName="t19",targetState="handle",cond=whenDispatch("parkcar"))
					transition(edgeName="t20",targetState="handle",cond=whenDispatch("pickupcar"))
					transition(edgeName="t21",targetState="stop",cond=whenDispatch("stoptrolley"))
				}	 
				state("handle") { //this:State
					action { //it:State
						
									STATE = `it.unibo.parkingmanagerservice.entity.trolley`.TrolleyState.WORKING 
									PAYLOAD = "{\"state\": \"${STATE}\", \"action\": \"${CURR_STAGE?.type}\", \"position\": {\"x\": \"${PLANNER.getPosX()}\", \"y\": \"${PLANNER.getPosY()}\"}}"
									TRIP_BUILDER.clear()
						updateResourceRep( PAYLOAD  
						)
						if( checkMsgContent( Term.createTerm("parkcar(SLOTNUM)"), Term.createTerm("parkcar(SLOTNUM)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("$name | Received request to park the car at the indoor to the slot ${payloadArg(0)}")
								 
												DEST = PARKING_SLOT_MAP.getAdiacentAllowedPositionBySlotnum(payloadArg(0))
												println("$name | Found slot at coordinates $DEST")
												if(DEST != null) {
													TRIP = TRIP_BUILDER.addParkTrip(DEST!!.first, DEST!!.second).build()
												} else
													println("$name | Unable to find a plan to go to the slot ${payloadArg(0)}")
						}
						if( checkMsgContent( Term.createTerm("pickupcar(SLOTNUM)"), Term.createTerm("pickupcar(SLOTNUM)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("$name | Received request to pickup the car at the slot ${payloadArg(0)}")
								 
												DEST = PARKING_SLOT_MAP.getAdiacentAllowedPositionBySlotnum(payloadArg(0))
												println("$name | Found slot at coordinates $DEST")
												if(DEST != null) {	
													TRIP = TRIP_BUILDER.addPickupTrip(DEST!!.first, DEST!!.second).build()
												} else
													println("$name | Unable to find a plan to go to the slot ${payloadArg(0)}")
						}
					}
					 transition( edgeName="goto",targetState="nextstage", cond=doswitchGuarded({ null != DEST  
					}) )
					transition( edgeName="goto",targetState="home", cond=doswitchGuarded({! ( null != DEST  
					) }) )
				}	 
				state("nextstage") { //this:State
					action { //it:State
						 
									CAN_GO = false
									if(TRIP != null) {
										while(TRIP!!.hasNext() && !CAN_GO) {
											CURR_STAGE = TRIP!!.next()
											println("$name ! CURRSTAGE = ${CURR_STAGE}")
											INTERRUPT = false
											
											when(CURR_STAGE!!.type) {
												`it.unibo.parkingmanagerservice.entity.trolley`.TripStageType.LOAD_CAR -> {
													CAN_GO = true
												}
												`it.unibo.parkingmanagerservice.entity.trolley`.TripStageType.UNLOAD_CAR -> {
													CAN_GO = true
												}
												else -> {
													PLANNER.setGoal(CURR_STAGE!!.destination.first, CURR_STAGE!!.destination.second)
													PLAN = PLANNER.doPlan()?.iterator()
													if(PLAN != null) {
														CAN_GO = true
													}
													if(CURR_STAGE!!.type == `it.unibo.parkingmanagerservice.entity.trolley`.TripStageType.MOVING_TO_HOME) {
														INTERRUPT = true
													} else {
														INTERRUPT = false
													}
												}
											}
										}	
									}
					}
					 transition( edgeName="goto",targetState="checkstage", cond=doswitchGuarded({ CAN_GO  
					}) )
					transition( edgeName="goto",targetState="home", cond=doswitchGuarded({! ( CAN_GO  
					) }) )
				}	 
				state("checkstage") { //this:State
					action { //it:State
						println("$name | Check stage")
					}
					 transition( edgeName="goto",targetState="elevator", cond=doswitchGuarded({ CURR_STAGE!!.type == `it.unibo.parkingmanagerservice.entity.trolley`.TripStageType.LOAD_CAR ||
								CURR_STAGE!!.type == `it.unibo.parkingmanagerservice.entity.trolley`.TripStageType.UNLOAD_CAR  
					}) )
					transition( edgeName="goto",targetState="nextaction", cond=doswitchGuarded({! ( CURR_STAGE!!.type == `it.unibo.parkingmanagerservice.entity.trolley`.TripStageType.LOAD_CAR ||
								CURR_STAGE!!.type == `it.unibo.parkingmanagerservice.entity.trolley`.TripStageType.UNLOAD_CAR  
					) }) )
				}	 
				state("elevator") { //this:State
					action { //it:State
						 
									EXPECTED_DIRECTION = DOOR_MAP.getDirection(PLANNER.getPosX(), PLANNER.getPosY()) ?: PARKING_SLOT_MAP.getDirection(PLANNER.getPosX(), PLANNER.getPosY())
									if(EXPECTED_DIRECTION != null) {
										while(EXPECTED_DIRECTION != PLANNER.getDirection()) {
						forward("cmd", "cmd(l)" ,"basicrobot" ) 
						delay(500) 
						
												PLANNER.doMove("l")
										}
									}
									
									when(CURR_STAGE!!.type) {
										`it.unibo.parkingmanagerservice.entity.trolley`.TripStageType.LOAD_CAR -> {
											println("$name | Car will be loaded")
											PLANNER.showMap()
											PLANNER.resetActions()
											PAYLOAD = "{\"state\": \"${STATE}\", \"action\": \"${CURR_STAGE!!.type}\", \"position\": {\"x\": \"${PLANNER.getPosX()}\", \"y\": \"${PLANNER.getPosY()}\"}}"
						updateResourceRep( PAYLOAD  
						)
						delay(3000) 
						
											println("$name | Car is loaded")
										}
										`it.unibo.parkingmanagerservice.entity.trolley`.TripStageType.UNLOAD_CAR-> {
											println("$name | Car will be unloaded")
											PLANNER.showMap()
											PLANNER.resetActions()
											PAYLOAD = "{\"state\": \"${STATE}\", \"action\": \"${CURR_STAGE!!.type}\", \"position\": {\"x\": \"${PLANNER.getPosX()}\", \"y\": \"${PLANNER.getPosY()}\"}}"
						updateResourceRep( PAYLOAD  
						)
						delay(3000) 
						
											println("$name | Car is unloaded")
										}
										else -> {}
									}
					}
					 transition( edgeName="goto",targetState="nextstage", cond=doswitch() )
				}	 
				state("nextaction") { //this:State
					action { //it:State
						
									CAN_GO = false
									if (null != TRIP && PLAN!!.hasNext()) {
										ACTION = PLAN!!.next()
										
										if (null != ACTION && !ACTION!!.isNoOp) {
											CAN_GO = true
										}
									}	
					}
					 transition( edgeName="goto",targetState="doaction", cond=doswitchGuarded({ CAN_GO  
					}) )
					transition( edgeName="goto",targetState="nextstage", cond=doswitchGuarded({! ( CAN_GO  
					) }) )
				}	 
				state("doaction") { //this:State
					action { //it:State
						
									CAN_GO = false
									if (ACTION.toString().equals("w")) {
						request("step", "step($STEP_TIME)" ,"basicrobot" )  
						
									CAN_GO = true
									} else {
						forward("cmd", "cmd($ACTION)" ,"basicrobot" ) 
						delay(500) 
						
									PLANNER!!.doMove(ACTION.toString())
									PAYLOAD = "{\"state\": \"${STATE}\", \"action\": \"${CURR_STAGE!!.type}\", \"position\": {\"x\": \"${PLANNER.getPosX()}\", \"y\": \"${PLANNER.getPosY()}\"}}"
						updateResourceRep( PAYLOAD  
						)
							
									}
					}
					 transition( edgeName="goto",targetState="waitstepdone", cond=doswitchGuarded({ CAN_GO  
					}) )
					transition( edgeName="goto",targetState="nextaction", cond=doswitchGuarded({! ( CAN_GO  
					) }) )
				}	 
				state("waitstepdone") { //this:State
					action { //it:State
						println("$name | Waiting step done...")
					}
					 transition(edgeName="t22",targetState="stop",cond=whenDispatch("stoptrolley"))
					transition(edgeName="t23",targetState="handle",cond=whenDispatchGuarded("parkcar",{ INTERRUPT  
					}))
					transition(edgeName="t24",targetState="handle",cond=whenDispatchGuarded("pickupcar",{ INTERRUPT  
					}))
					transition(edgeName="t25",targetState="handlestepdone",cond=whenReply("stepdone"))
				}	 
				state("handlestepdone") { //this:State
					action { //it:State
						
									PAYLOAD = "{\"state\": \"${STATE}\", \"action\": \"${CURR_STAGE!!.type}\", \"position\": {\"x\": \"${PLANNER.getPosX()}\", \"y\": \"${PLANNER.getPosY()}\"}}"
						updateResourceRep( PAYLOAD  
						)
					}
					 transition( edgeName="goto",targetState="nextaction", cond=doswitch() )
				}	 
				state("stop") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("stepdone(V)"), Term.createTerm("stepdone(V)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 PLANNER!!.doMove(ACTION.toString())  
						}
						
									STATE = `it.unibo.parkingmanagerservice.entity.trolley`.TrolleyState.STOPPED
									PAYLOAD = "{\"state\": \"${STATE}\", \"action\": \"${CURR_STAGE?.type}\", \"position\": {\"x\":\"${PLANNER.getPosX()}\", \"y\": \"${PLANNER.getPosY()}\"}}"
						updateResourceRep( PAYLOAD  
						)
					}
					 transition(edgeName="t26",targetState="nextaction",cond=whenDispatch("resumetrolley"))
					transition(edgeName="t27",targetState="stop",cond=whenReply("stepdone"))
				}	 
			}
		}
}
