/* Generated by AN DISI Unibo */ 
package it.unibo.weightsensoractor

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Weightsensoractor ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				var weight : Float = 0.0F
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						discardMessages = true
						println("WEIGHT SENSOR | Started...")
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						println("WEIGHT SENSOR | weight: $weight")
					}
					 transition(edgeName="t00",targetState="measure",cond=whenDispatch("measureweight"))
				}	 
				state("measure") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("measureweight(X)"), Term.createTerm("measureweight(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
												val value = payloadArg(0) 
												weight = value.toFloat()
						}
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
}
