/* Generated by AN DISI Unibo */ 
package it.unibo.weightsensoractor

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Weightsensoractor ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 
				val weightsensor = it.unibo.devices.DeviceManager.getDevice("indoor_sensor")
				var weight : Double
				var state = ""
				var jsonState = ""
				 
				var POLLING_MS : Long = 1000
				val min_weight = 0.1
				
				if (weightsensor == null) {
					println("$name | Unable to use the weight sensor")
					System.exit(-1)
				}
				
				weightsensor as it.unibo.weightsensor.AbstractWeightSensor
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name | Started...")
						
									weight = weightsensor.readWeight()
									if (weight < min_weight)
										state = "OFF"
									else 
										state = "ON"
										
									jsonState = "{\"data\": \"$weight\", \"state\": \"$state\"}"
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						println("$name | State: $jsonState")
					}
					 transition(edgeName="t02",targetState="setpolling",cond=whenDispatch("dopolling"))
				}	 
				state("setpolling") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("dopolling(TIME)"), Term.createTerm("dopolling(TIME)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 POLLING_MS = payloadArg(0).toLong()  
						}
						println("$name | Start polling with $POLLING_MS ms")
					}
					 transition( edgeName="goto",targetState="polling", cond=doswitch() )
				}	 
				state("polling") { //this:State
					action { //it:State
						
									weight = weightsensor.readWeight()
									
									if (state.toUpperCase().equals("OFF") && weight > min_weight) {
										state = "ON"
						emit("weighton", "weighton(ON)" ) 
						
									} else if (state.toUpperCase().equals("ON") && weight < min_weight) {
										state = "OFF"
						emit("weightoff", "weightoff(OFF)" ) 
						
									}
									
									jsonState = "{\"data\": \"$weight\", \"state\": \"$state\"}"
						updateResourceRep( jsonState  
						)
						stateTimer = TimerActor("timer_polling", 
							scope, context!!, "local_tout_weightsensoractor_polling", POLLING_MS )
					}
					 transition(edgeName="t03",targetState="polling",cond=whenTimeout("local_tout_weightsensoractor_polling"))   
					transition(edgeName="t04",targetState="work",cond=whenDispatch("stoppolling"))
					transition(edgeName="t05",targetState="setpolling",cond=whenDispatch("dopolling"))
				}	 
			}
		}
}
