/* Generated by AN DISI Unibo */ 
package it.unibo.itoccactor

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Itoccactor ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 	
				val ITOCC = it.unibo.parkingmanagerservice.entity.timer.Timer.get().ITOCC
				var REACHED = false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name | Started...")
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						 
									if(REACHED) {
										REACHED = false
						updateResourceRep( "reached" 
						)
						 } else {  
						updateResourceRep( "work" 
						)
						 }  
						println("$name | Waiting for command")
					}
					 transition(edgeName="t7",targetState="count",cond=whenDispatch("startitocc"))
					transition(edgeName="t8",targetState="work",cond=whenDispatch("stopcount"))
				}	 
				state("count") { //this:State
					action { //it:State
						println("$name | Start ITOCC count...")
						updateResourceRep( "count" 
						)
						stateTimer = TimerActor("timer_count", 
							scope, context!!, "local_tout_itoccactor_count", ITOCC )
					}
					 transition(edgeName="t9",targetState="reached",cond=whenTimeout("local_tout_itoccactor_count"))   
					transition(edgeName="t10",targetState="count",cond=whenDispatch("startitocc"))
					transition(edgeName="t11",targetState="work",cond=whenDispatch("stopcount"))
				}	 
				state("reached") { //this:State
					action { //it:State
						println("$name | ITOCC reached")
						emit("itoccreached", "itoccreached(REACHED)" ) 
						updateResourceRep( "reached"  
						)
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
}
