/* Generated by AN DISI Unibo */ 
package it.unibo.outsonaractor

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Outsonaractor ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				var outsonar = it.unibo.devices.DeviceManager.getDevice("outsonar")
				var THRESHOLD_DISTANCE = it.unibo.outsonar.AbstractOutSonar.getThresholdDistance()
				var POLLING_MS : Long = 1000
				var distance : Int
				var state : String = ""
				var jsonState : String = ""
				
				if (outsonar == null) {
					println("$name | Unable to use outsonar")
					System.exit(-1)
				}
				
				outsonar as it.unibo.outsonar.AbstractOutSonar
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name | Started...")
						
									distance = outsonar.readDistance()	
									
									if (distance > THRESHOLD_DISTANCE)	{
										state = "OFF"
									} else {
										state = "ON"
									}
									
									jsonState = "{\"data\": \"$distance\", \"state\": \"$state\"}"
						updateResourceRep( jsonState  
						)
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						println("$name | State: ${jsonState}")
					}
					 transition(edgeName="to8",targetState="setpolling",cond=whenDispatch("dopolling"))
				}	 
				state("setpolling") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("dopolling(TIME)"), Term.createTerm("dopolling(TIME)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 POLLING_MS = payloadArg(0).toLong()  
						}
						println("$name | Start polling with $POLLING_MS ms")
					}
					 transition( edgeName="goto",targetState="polling", cond=doswitch() )
				}	 
				state("polling") { //this:State
					action { //it:State
						
									distance = outsonar.readDistance()
									
									if (state.toUpperCase().equals("OFF") && distance < THRESHOLD_DISTANCE) {
										state = "ON"	
						emit("outsonaron", "outsonaron(ON)" ) 
						
									} else if (state.toUpperCase().equals("ON") && distance > THRESHOLD_DISTANCE) {
										state = "OFF"	
						emit("outsonaroff", "outsonaroff(OFF)" ) 
								
									}
									
									jsonState = "{\"data\": \"$distance\", \"state\": \"$state\"}"
						updateResourceRep( jsonState  
						)
						stateTimer = TimerActor("timer_polling", 
							scope, context!!, "local_tout_outsonaractor_polling", POLLING_MS )
					}
					 transition(edgeName="to9",targetState="polling",cond=whenTimeout("local_tout_outsonaractor_polling"))   
					transition(edgeName="to10",targetState="work",cond=whenDispatch("stoppolling"))
					transition(edgeName="to11",targetState="setpolling",cond=whenDispatch("dopolling"))
				}	 
			}
		}
}
