/* Generated by AN DISI Unibo */ 
package it.unibo.outsonaractor

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Outsonaractor ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 
				val outsonar = it.unibo.devices.DeviceManager.getDevice("outsonar")
				var distance : Int
				
				if (outsonar == null) {
					println("$name | Unable to use outsonar")
					System.exit(-1)
				}
				
				outsonar as it.unibo.outsonar.AbstractOutSonar
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name | Started...")
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						 distance = outsonar.readDistance()  
						updateResourceRep( distance.toString()  
						)
						println("$name | Distance: $distance")
					}
					 transition(edgeName="t00",targetState="work",cond=whenDispatch("updateoutsonar"))
				}	 
			}
		}
}
