/* Generated by AN DISI Unibo */ 
package it.unibo.dtfreeactor

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Dtfreeactor ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				val DTFREE = it.unibo.parkingmanagerservice.entity.timer.Timer.get().DTFREE
				var REACHED = false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name | Started...")
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						 
									if(REACHED) {
										REACHED = false
						updateResourceRep( "reached" 
						)
						 } else {  
						updateResourceRep( "work" 
						)
						 }  
						println("$name | Waiting for command")
					}
					 transition(edgeName="t12",targetState="count",cond=whenDispatch("startdtfree"))
					transition(edgeName="t13",targetState="work",cond=whenDispatch("stopcount"))
				}	 
				state("count") { //this:State
					action { //it:State
						println("$name | Start DTFREE count...")
						updateResourceRep( "count"  
						)
						stateTimer = TimerActor("timer_count", 
							scope, context!!, "local_tout_dtfreeactor_count", DTFREE )
					}
					 transition(edgeName="t14",targetState="reached",cond=whenTimeout("local_tout_dtfreeactor_count"))   
					transition(edgeName="t15",targetState="count",cond=whenDispatch("startdtfree"))
					transition(edgeName="t16",targetState="work",cond=whenDispatch("stopcount"))
				}	 
				state("reached") { //this:State
					action { //it:State
						println("$name | DTFREE reached")
						emit("dtfreereached", "dtfreereached(REACHED)" ) 
						updateResourceRep( "reached"  
						)
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
}
