/* Generated by AN DISI Unibo */ 
package it.unibo.temperatureactor

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Temperatureactor ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 var type : String  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name | Started...")
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						println("$name | Working...")
					}
					 transition(edgeName="t18",targetState="handlecriticaltemp",cond=whenEvent("criticaltemp"))
				}	 
				state("handlecriticaltemp") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("criticaltemp(X)"), Term.createTerm("criticaltemp(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												type = payloadArg(0)
												if (type.toUpperCase().equals("CRITICAL")) {
								println("$name | Critical temp reached")
								forward("fanon", "fanon(ON)" ,"fanactor" ) 
								
												} else if (type.toUpperCase().equals("NORMAL")) {	
								println("$name | Normal temp reached")
								forward("fanon", "fanon(ON)" ,"fanactor" ) 
								
												}	
						}
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
}
